name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  unit_test_windows:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest
    
    env:
      Solution_Name: source/StepBro.sln
      Test_Project_Path: source/Test/StepBro.Core.Test/StepBro.Core.Test.csproj
  
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Install dependencies
      run: dotnet restore source/Test/StepBro.Core.Test/StepBro.Core.Test.csproj
      
    - name: Build
      run: dotnet build source/Test/StepBro.Core.Test/StepBro.Core.Test.csproj -c ${{ matrix.configuration }}

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test source/Test/StepBro.Core.Test/StepBro.Core.Test.csproj

    - name: Install dependencies
      run: dotnet restore source/Test/StepBro.HostSupport.Test/StepBro.HostSupport.Test.csproj
      
    - name: Build
      run: dotnet build source/Test/StepBro.HostSupport.Test/StepBro.HostSupport.Test.csproj -c ${{ matrix.configuration }}

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test source/Test/StepBro.HostSupport.Test/StepBro.HostSupport.Test.csproj
  
  
  unit_test_ubuntu:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest
    
    env:
      Solution_Name: source/StepBro.sln
      Test_Project_Path: source/Test/StepBro.Core.Test/StepBro.Core.Test.csproj
  
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Install dependencies
      run: dotnet restore source/Test/StepBro.Core.Test/StepBro.Core.Test.csproj
      
    - name: Build
      run: dotnet build source/Test/StepBro.Core.Test/StepBro.Core.Test.csproj -c ${{ matrix.configuration }}

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test source/Test/StepBro.Core.Test/StepBro.Core.Test.csproj
  
    - name: Install dependencies
      run: dotnet restore source/Test/StepBro.HostSupport.Test/StepBro.HostSupport.Test.csproj
      
    - name: Build
      run: dotnet build source/Test/StepBro.HostSupport.Test/StepBro.HostSupport.Test.csproj -c ${{ matrix.configuration }}

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test source/Test/StepBro.HostSupport.Test/StepBro.HostSupport.Test.csproj
  
  
  
  build_and_test_stepbro:

    strategy:
      matrix:
        configuration: [Debug, Release]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    env:
      Solution_Name: source/StepBro.sln
      Test_Project_Path: source/Test/StepBro.Core.Test/StepBro.Core.Test.csproj



    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Install dependencies
      run: dotnet restore source/StepBro.sln /p:EnableWindowsTargeting=true
      
    - name: Build
      run: dotnet build source/StepBro.sln /p:EnableWindowsTargeting=true -c ${{ matrix.configuration }}
        
    # TODO: Out-commented because stepbro --version has exit code -1 for some reason, when it is fixed this can be re-added
    # - name: Run StepBro Version Check
    #   run: .\source\bin\stepbro.exe --version
        
    - name: Run StepBro Consoletest
      run: ./source/bin/stepbro "./test files/smoketest/ConsoleTest.sbs" -v -e HelloStepBro --exitcode Verdict

    - name: Run StepBro Smoketest
      run: ./source/bin/stepbro "./test files/smoketest/smoketest.sbs" -v -e AllTests -m FormalTest --exitcode SubVerdict

    - name: Run SerialTestConnection test
      run: ./source/bin/stepbro "./test files/ModuleTests/SerialTestConnection/SerialTestConnectionTests.sbs" -v -e SerialTestConnectionOfflineTests -m FormalTest --exitcode SubVerdict

    - name: Run ExecutionHelper test
      if: ${{ matrix.os == 'windows-latest' }}
      run: ./source/bin/stepbro "./test files/ModuleTests/ExecutionHelper/ExecutionHelperTests.sbs" -v -e ExecutionHelperTests -m FormalTest --exitcode SubVerdict
